-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZtCeePb1luyCLth6
PfVljYv+qQPvIHipsicB38crmDmgCgYIKoZIzj0DAQehRANCAAT/f5a4twXNj+Gw
lsFEeSbaAFidi4xiQhmipSO4eigXSsWwLtJ3fVWExz38rg2aY/sAbzUgs0KOfCMy
3W6/SaF2
-----END PRIVATE KEY-----