import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
} from "react";
import { useColorScheme } from "react-native";
import { customFetch } from "@workspace/api-client-react";
import { useAuth } from "./AuthContext";
import { DARK_COLORS, LIGHT_COLORS } from "@/constants/theme";

type Language = "fr" | "en";
type Theme = "dark" | "light" | "system";
type Units = "metric" | "imperial";

interface Preferences {
  language: Language;
  theme: Theme;
  units: Units;
}

interface PreferencesContextValue extends Preferences {
  resolvedTheme: "dark" | "light";
  setLanguage: (lang: Language) => void;
  setTheme: (theme: Theme) => void;
  setUnits: (units: Units) => void;
  persist: (partial: Partial<Preferences>) => Promise<void>;
  formatWeight: (kg: number | null | undefined) => string;
  formatDistance: (km: number | null | undefined) => string;
}

const PreferencesContext = createContext<PreferencesContextValue>({
  language: "fr",
  theme: "dark",
  units: "metric",
  resolvedTheme: "dark",
  setLanguage: () => {},
  setTheme: () => {},
  setUnits: () => {},
  persist: async () => {},
  formatWeight: (kg) => (kg != null ? `${kg} kg` : "—"),
  formatDistance: (km) => (km != null ? `${km} km` : "—"),
});

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const { isAuthenticated } = useAuth();
  const systemColorScheme = useColorScheme();
  const [language, setLanguageState] = useState<Language>("fr");
  const [theme, setThemeState] = useState<Theme>("dark");
  const [units, setUnitsState] = useState<Units>("metric");

  const resolvedTheme: "dark" | "light" =
    theme === "system"
      ? (systemColorScheme === "light" ? "light" : "dark")
      : theme;

  useEffect(() => {
    if (!isAuthenticated) return;
    customFetch<{ language?: string; theme?: string; units?: string }>(
      "/api/users/me/profile"
    )
      .then((data) => {
        if (data.language === "en") setLanguageState("en");
        else setLanguageState("fr");
        if (data.theme === "light") setThemeState("light");
        else if (data.theme === "system") setThemeState("system");
        else setThemeState("dark");
        if (data.units === "imperial") setUnitsState("imperial");
        else setUnitsState("metric");
      })
      .catch(() => {});
  }, [isAuthenticated]);

  const persist = useCallback(async (partial: Partial<Preferences>) => {
    await customFetch("/api/users/me/profile", {
      method: "PUT",
      body: JSON.stringify(partial),
    });
  }, []);

  const setLanguage = useCallback(
    (lang: Language) => {
      setLanguageState(lang);
      persist({ language: lang }).catch(() => {});
    },
    [persist]
  );

  const setTheme = useCallback(
    (t: Theme) => {
      setThemeState(t);
      persist({ theme: t }).catch(() => {});
    },
    [persist]
  );

  const setUnits = useCallback(
    (u: Units) => {
      setUnitsState(u);
      persist({ units: u }).catch(() => {});
    },
    [persist]
  );

  const formatWeight = useCallback(
    (kg: number | null | undefined): string => {
      if (kg == null) return "—";
      if (units === "imperial") {
        return `${(kg * 2.20462).toFixed(1)} lbs`;
      }
      return `${kg} kg`;
    },
    [units]
  );

  const formatDistance = useCallback(
    (km: number | null | undefined): string => {
      if (km == null) return "—";
      if (units === "imperial") {
        return `${(km * 0.621371).toFixed(2)} mi`;
      }
      return `${km} km`;
    },
    [units]
  );

  return (
    <PreferencesContext.Provider
      value={{
        language,
        theme,
        units,
        resolvedTheme,
        setLanguage,
        setTheme,
        setUnits,
        persist,
        formatWeight,
        formatDistance,
      }}
    >
      {children}
    </PreferencesContext.Provider>
  );
}

export function usePreferences() {
  return useContext(PreferencesContext);
}

export function useResolvedTheme(): "dark" | "light" {
  return useContext(PreferencesContext).resolvedTheme;
}

export function useFormatWeight() {
  return useContext(PreferencesContext).formatWeight;
}

export function useFormatDistance() {
  return useContext(PreferencesContext).formatDistance;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  fr: {
    kg: "kg", km: "km", lbs: "lbs", mi: "mi",
    weight: "Poids", height: "Taille",
    primary_goal: "Objectif principal", secondary_goal: "Objectif secondaire",
    fitness_level: "Niveau de forme",
    training_context: "Contexte d'entraînement",
    available_days: "Jours d'entraînement",
    training_location: "Lieu d'entraînement",
    equipment: "Équipement disponible",
    session_duration: "Durée de séance",
    session_min: "Minimum", session_max: "Maximum",
    injuries: "Blessures / Restrictions permanentes",
    no_restrictions: "Aucune restriction renseignée",
    exercises: "Exercices", avoided_exercises: "Exercices à éviter",
    favorite_exercises: "Exercices préférés",
    add_exercise: "Ajouter un exercice...",
    from_library: "Depuis la bibliothèque",
    select_exercises: "Sélectionner des exercices",
    done: "Terminer", none: "Aucun",
    preferences: "Préférences",
    language_label: "Langue", theme_label: "Thème", units_label: "Unités",
    health_apps: "Applications santé",
    sync_health_data: "Synchronise tes données de santé avec ADAPT.",
    privacy: "Confidentialité",
    privacy_desc: "Contrôle ce que ton coach peut voir de ton profil.",
    share_weight: "Partager le poids",
    share_sleep: "Partager le sommeil",
    share_heart_rate: "Partager la fréquence cardiaque",
    share_body_fat: "Partager la masse grasse",
    share_context: "Partager le contexte d'entraînement",
    coach_only: "Profil visible par le coach uniquement",
    profile_private: "Profil entièrement privé",
    notifications: "Notifications",
    silent_mode: "Désactiver toutes les notifications",
    morning_notif: "Notification check-in matin",
    session_reminder: "Rappel de séance",
    progress_update: "Mise à jour de progression",
    coach_messages: "Messages du coach",
    save: "Enregistrer", cancel: "Annuler", edit: "Modifier",
    connect: "Connecter", disconnect: "Déconnecter",
    connected: "Connecté", not_connected: "Non connecté",
    achievement: "Succès débloqué",
    weekly_recap: "Récapitulatif hebdo",
    soon: "Bientôt disponible",
    soon_msg: "sera disponible dans une prochaine mise à jour.",
    privacy_visibility: "Visibilité du profil",
    shared_data: "Données partagées avec le coach",
    completion_hint_low: "Complète ton profil pour personnaliser ton entraînement",
    completion_hint_mid: "Quelques informations manquent encore",
    no_injury: "Aucune restriction renseignée",
    units_metric: "Kg / Km",
    units_imperial: "Lbs / Mi",
    lang_fr: "Français",
    lang_en: "English",
    theme_dark: "Sombre",
    theme_light: "Clair",
    theme_system: "Automatique",
    goals: "Objectifs",
    privacy_settings: "Paramètres de confidentialité",
    lang_label: "Langue",
    morning_notif_hour: "Heure de rappel matin",
    notif_types_label: "Types de notifications",
    silent_mode_label: "Mode silencieux",
    privacy_data_desc: "Ces données sont transmises à ton coach sur toutes ses vues. Désactiver un interrupteur masque la donnée partout.",
    privacy_visibility_desc: "Ces paramètres contrôlent la visibilité globale de ton profil. Cumulatifs avec les données partagées ci-dessus.",
    health_coming_soon: "Bientôt disponible",
    error: "Erreur",
    success: "Succès",
    warning: "Attention",
    info: "Information",
    confirm: "Confirmer",
    yes: "Oui",
    no: "Non",
    ok: "OK",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    continue: "Continuer",
    close: "Fermer",
    delete: "Supprimer",
    add: "Ajouter",
    remove: "Retirer",
    update: "Mettre à jour",
    loading: "Chargement…",
    retry: "Réessayer",
    refresh: "Actualiser",
    search: "Rechercher",
    filter: "Filtrer",
    all: "Tous",
    today: "Aujourd'hui",
    yesterday: "Hier",
    tomorrow: "Demain",
    week: "Semaine",
    month: "Mois",
    year: "Année",
    day: "Jour",
    hour: "Heure",
    minute: "Minute",
    second: "Seconde",
    minutes: "minutes",
    seconds: "secondes",
    hours: "heures",
    days: "jours",
    weeks: "semaines",
    months: "mois",
    home: "Accueil",
    session_tab: "Séance",
    stats_tab: "Stats",
    messages_tab: "Messages",
    profile_tab: "Profil",
    welcome: "Bienvenue",
    hello: "Bonjour",
    good_morning: "Bonjour",
    good_afternoon: "Bon après-midi",
    good_evening: "Bonsoir",
    start_session: "Démarrer la séance",
    start: "C'est parti !",
    resume: "Reprendre",
    pause: "Pause",
    stop: "Arrêter",
    finish: "Terminer",
    skip: "Passer",
    rest: "Repos",
    sets: "Séries",
    reps: "Répétitions",
    set: "Série",
    rep: "Rep",
    duration: "Durée",
    rpe: "RPE",
    notes: "Notes",
    note: "Note",
    feedback: "Feedback",
    difficulty: "Difficulté",
    easy: "Facile",
    medium: "Moyen",
    hard: "Difficile",
    too_easy: "Trop facile",
    just_right: "Parfait",
    too_hard: "Trop difficile",
    cannot_start_session: "Impossible de démarrer cette séance. Réessaie.",
    cannot_start_program: "Impossible de démarrer le programme. Réessaie.",
    cannot_log_exercise: "Impossible d'enregistrer l'exercice.",
    cannot_save: "Impossible d'enregistrer. Réessaie.",
    cannot_load: "Impossible de charger les données.",
    network_error: "Erreur réseau. Vérifie ta connexion.",
    session_completed: "Séance terminée !",
    great_job: "Bien joué !",
    keep_going: "Continue comme ça !",
    no_session_today: "Pas de séance aujourd'hui",
    next_session: "Prochaine séance",
    upcoming_sessions: "Séances à venir",
    history: "Historique",
    library: "Bibliothèque",
    programs: "Programmes",
    challenges: "Défis",
    badges: "Badges",
    guides: "Guides",
    nutrition: "Nutrition",
    sleep: "Sommeil",
    steps: "Pas",
    heart_rate: "Fréquence cardiaque",
    body_fat: "Masse grasse",
    bmi: "IMC",
    calories: "Calories",
    protein: "Protéines",
    carbs: "Glucides",
    fat: "Lipides",
    water: "Eau",
    checkin: "Check-in",
    morning_checkin: "Check-in du matin",
    daily_checkin: "Check-in quotidien",
    mood: "Humeur",
    energy: "Énergie",
    motivation: "Motivation",
    soreness: "Courbatures",
    stress: "Stress",
    coach: "Coach",
    athlete: "Athlète",
    message_placeholder: "Écris un message…",
    send: "Envoyer",
    no_messages: "Aucun message",
    new_message: "Nouveau message",
    login: "Connexion",
    register: "Inscription",
    logout: "Déconnexion",
    email: "Email",
    password: "Mot de passe",
    confirm_password: "Confirmer le mot de passe",
    forgot_password: "Mot de passe oublié ?",
    reset_password: "Réinitialiser le mot de passe",
    sign_in: "Se connecter",
    sign_up: "S'inscrire",
    invalid_credentials: "Identifiants invalides",
    required_field: "Champ requis",
    invalid_email: "Email invalide",
    password_too_short: "Mot de passe trop court",
    passwords_dont_match: "Les mots de passe ne correspondent pas",
    onboarding_welcome: "Bienvenue sur ADAPT",
    onboarding_goal: "Quel est ton objectif ?",
    onboarding_fitness: "Quel est ton niveau ?",
    onboarding_profile: "Ton profil",
    onboarding_invite: "Code d'invitation",
    enter_invite_code: "Entrer le code",
    skip_for_now: "Passer pour l'instant",
    name: "Nom",
    first_name: "Prénom",
    last_name: "Nom",
    age: "Âge",
    gender: "Genre",
    male: "Homme",
    female: "Femme",
    other: "Autre",
    birthdate: "Date de naissance",
    no_data: "Aucune donnée",
    empty_state: "Rien à afficher pour le moment",
    coming_soon: "Bientôt disponible",
    about: "À propos",
    version: "Version",
    terms: "Conditions d'utilisation",
    privacy_policy: "Politique de confidentialité",
    contact: "Contact",
    help: "Aide",
    settings: "Paramètres",
    account: "Compte",
    delete_account: "Supprimer le compte",
    confirm_logout: "Veux-tu vraiment te déconnecter ?",
    confirm_delete: "Cette action est irréversible. Continuer ?",
    saved: "Enregistré",
    updated: "Mis à jour",
    deleted: "Supprimé",
    sent: "Envoyé",
    copied: "Copié",
    profile_completed: "PROFIL COMPLÉTÉ",
    save_error: "Impossible de sauvegarder les modifications",
    injuries_placeholder: "Ex: douleur genou gauche, épaule fragile...",
    tap_pencil_to_edit: "Appuie sur l'icône crayon pour modifier",
    health_integration_coming: "Intégration disponible prochainement.",
    day_short_lun: "L",
    day_short_mar: "M",
    day_short_mer: "Me",
    day_short_jeu: "J",
    day_short_ven: "V",
    day_short_sam: "S",
    day_short_dim: "D",
    loc_gym: "Salle",
    loc_home: "Maison",
    loc_outdoor: "Extérieur",
    equip_barbell: "Barre",
    equip_dumbbell: "Haltères",
    equip_kettlebell: "Kettlebell",
    equip_machine: "Machines",
    equip_cable: "Poulie",
    equip_bodyweight: "Poids du corps",
    equip_bands: "Élastiques",
    equip_trx: "TRX",
    goal_strength: "Force",
    goal_muscle: "Prise de masse",
    goal_fat_loss: "Perte de poids",
    goal_performance: "Performance",
    goal_health: "Santé",
    goal_aesthetic: "Esthétique",
    goal_fitness: "Forme générale",
    level_beginner: "Débutant",
    level_intermediate: "Intermédiaire",
    level_advanced: "Avancé",
    level_expert: "Expert",
    sgoal_mobility: "Mobilité",
    sgoal_endurance: "Endurance",
    sgoal_flexibility: "Souplesse",
    sgoal_power: "Explosivité",
    sgoal_balance: "Équilibre",
    sgoal_stress: "Bien-être",
    sgoal_sport: "Sport spécifique",
    privacy_share_weight_label: "Poids corporel",
    privacy_share_sleep_label: "Qualité du sommeil",
    privacy_share_hr_label: "Fréquence cardiaque",
    privacy_share_bf_label: "Masse grasse (%)",
    privacy_share_context_label: "Contexte d'entraînement",
    auth_tagline: "L'entraînement qui s'adapte à toi.",
    no_account_yet: "Pas encore de compte ?",
    create_account: "Créer un compte",
    create_my_account: "Créer mon compte",
    create_account_title: "CRÉER UN COMPTE",
    join_adapt: "Rejoins ADAPT",
    already_have_account: "Déjà un compte ?",
    sign_in_link: "Se connecter",
    forgot_pwd_title: "MOT DE PASSE",
    forgot_pwd_title_sub: "OUBLIÉ",
    forgot_pwd_subtitle: "Saisis ton adresse email. Tu recevras un lien pour choisir un nouveau mot de passe.",
    send_link_btn: "ENVOYER LE LIEN",
    email_sent_title: "Email envoyé !",
    email_sent_text: "Si un compte existe avec cette adresse, tu recevras un lien de réinitialisation dans quelques minutes. Vérifie aussi tes spams.",
    back_to_login: "Retour à la connexion",
    email_required: "L'adresse email est requise",
    email_password_required: "L'email et le mot de passe sont requis",
    all_fields_required: "Tous les champs sont requis",
    pwd_min_8: "Le mot de passe doit contenir au moins 8 caractères",
    pwd_strength_weak: "Faible",
    pwd_strength_medium: "Moyen",
    pwd_strength_good: "Bon",
    pwd_strength_strong: "Fort",
    pwd_min_chars_placeholder: "Min. 8 caractères",
    new_pwd_title: "NOUVEAU",
    new_pwd_title_sub: "MOT DE PASSE",
    new_password: "Nouveau mot de passe",
    confirm_password_label: "Confirmer le mot de passe",
    change_my_password: "CHANGER MON MOT DE PASSE",
    pwd_updated: "Mot de passe mis à jour !",
    redirecting_login: "Redirection vers la connexion…",
    invalid_link: "Lien invalide",
    invalid_link_subtitle: "Ce lien de réinitialisation est invalide ou a expiré.",
    request_new_link: "Demander un nouveau lien",
    invalid_or_expired: "Lien invalide ou expiré.",
    error_generic: "Une erreur est survenue. Réessaie.",
    not_found_title: "Cet écran n'existe pas.",
    go_home: "Retour à l'accueil",
    no_session_subtitle: "Aucune séance n'est programmée pour aujourd'hui. Ton coach n'a pas encore attribué de programme.",
    no_session_uppercase: "AUCUNE SÉANCE",
    in_person: "PRÉSENTIEL",
    online: "EN LIGNE",
    adapt_score: "ADAPT SCORE",
    edit_checkin_today: "Modifier mon check-in du jour",
    you_will_need: "TU AURAS BESOIN DE",
    coach_notes: "NOTES DU COACH",
    exercises_count_label: "EXERCICES",
    min_label: "MIN",
    guided: "GUIDÉ",
    board: "TABLEAU",
    show_details: "Voir le détail",
    hide_details: "Masquer",
    loads_at_pct: "Charges à",
    exercise: "EXERCICE",
    planned: "PRÉVU",
    adapted: "ADAPTÉ",
    cannot_validate_session: "Impossible de valider la séance",
    cannot_confirm_presence: "Impossible de confirmer la présence",
    notifications_title: "Notifications",
    no_notifications: "Aucune notification",
    mark_all_read: "Tout marquer comme lu",
    weekly_recap_title: "Récap hebdo",
    weekly_recap_empty: "Aucun récapitulatif disponible",
    badges_title: "Badges",
    badges_empty: "Aucun badge débloqué",
    challenges_title: "Défis",
    join_challenge: "Rejoindre le défi",
    progress: "Progression",
    leaderboard: "Classement",
    days_remaining: "jours restants",
    checkin_title: "Check-in du jour",
    checkin_intro: "Prends 30 secondes pour évaluer ton état du jour.",
    sleep_q: "Comment as-tu dormi ?",
    energy_q: "Quel est ton niveau d'énergie ?",
    stress_q: "Niveau de stress ?",
    soreness_q: "Courbatures ?",
    motivation_q: "Motivation ?",
    pain_q: "As-tu des douleurs ?",
    pain_notes_placeholder: "Décris brièvement (optionnel)",
    cycle_phase_q: "Phase du cycle (optionnel)",
    submit_checkin: "Valider mon check-in",
    checkin_done: "Check-in enregistré !",
    checkin_done_subtitle: "Ta séance du jour s'adapte à ton état.",
    see_my_session: "Voir ma séance",
    guides_title: "Guides",
    guides_empty: "Aucun guide disponible",
    library_title: "Bibliothèque",
    library_empty: "Aucune séance disponible",
    custom_session_title: "Séance personnalisée",
    add_to_session: "Ajouter à la séance",
    start_custom: "Démarrer la séance",
    chat_placeholder: "Écris un message...",
    onboarding_welcome_title: "Bienvenue sur ADAPT",
    onboarding_welcome_subtitle: "L'entraînement qui s'adapte à toi.",
    get_started: "Commencer",
    onboarding_goal_q: "Quel est ton objectif ?",
    onboarding_fitness_q: "Quel est ton niveau ?",
    onboarding_profile_q: "Parle-nous de toi",
    onboarding_invite_q: "As-tu un code d'invitation ?",
    invite_code_placeholder: "Code d'invitation",
    validate: "Valider",
    skip_step: "Passer",
    tutorial_title: "Comment ça marche",
    finish_tutorial: "C'est compris",
    session_complete_title: "Séance terminée !",
    session_complete_subtitle: "Bravo, tu peux être fier de toi !",
    rate_session_q: "Comment t'es-tu senti ?",
    submit_rating: "Valider",
    free_session_title: "Séance libre",
    free_session_intro: "Crée ta séance à la volée.",
    add_exercise_btn: "Ajouter un exercice",
    end_session: "Terminer la séance",
    history_title: "Historique",
    history_empty: "Aucune séance terminée",
    feedback_title: "Ton ressenti",
    submit_feedback: "Envoyer",
    your_session: "Ta séance",
    detail_title: "Détail de la séance",
    no_exercises: "Aucun exercice",
    sets_label: "séries",
    reps_label: "reps",
    rest_label: "repos",
    badge_cat_special: "Spécial",
    badge_cat_streak: "Streak",
    badge_cat_sessions: "Séances",
    badge_cat_pr: "Records",
    my_badges: "MES BADGES",
    weekly_recap_uppercase: "BILAN SEMAINE",
    calculating: "Calcul en cours...",
    no_data_week: "Pas encore de données pour cette semaine.",
    sessions_uppercase: "SÉANCES",
    performances_uppercase: "PERFORMANCES",
    vs_prev_week: "vs semaine précédente :",
    avg_adapt_score: "Score ADAPT moyen",
    avg_rpe: "RPE moyen",
    total_volume: "Volume total",
    new_records: "Nouveaux records",
    no_session_this_week: "Aucune séance cette semaine. Commence aujourd'hui !",
    just_now: "À l'instant",
    minutes_ago: "Il y a {0} min",
    hours_ago: "Il y a {0}h",
    days_ago: "Il y a {0}j",
    mark_all_short: "Tout lire",
    challenge_progress_title: "Progression du défi",
    challenge_completed: "Défi terminé",
    challenge_failed: "Défi échoué",
    sleep_hours: "Heures de sommeil",
    very_bad: "Très mauvais",
    bad: "Mauvais",
    ok_label: "Correct",
    good: "Bon",
    very_good: "Très bon",
    very_low: "Très faible",
    low: "Faible",
    high: "Élevé",
    very_high: "Très élevé",
    save_checkin: "Valider mon check-in",
    saving: "Enregistrement…",
    welcome_aboard: "Bienvenue à bord !",
    your_score_today: "Ton score du jour",
    session_will_adapt: "Ta séance s'adapte à ton état.",
    next_step: "Prochaine étape",
    log_in: "Se connecter",
    have_invite: "J'ai un code",
    skip_invite: "Continuer sans code",
    invite_sent: "Demande envoyée à ton coach !",
    invite_invalid: "Code invalide",
    your_first_name: "Ton prénom",
    your_last_name: "Ton nom",
    select_goal: "Sélectionne ton objectif principal",
    select_level: "Sélectionne ton niveau",
    finish_setup: "Terminer",
    free_session_intro_long: "Crée ta séance à la volée. Ajoute les exercices que tu veux faire.",
    no_exercise_added: "Aucun exercice ajouté",
    end_free_session: "Terminer la séance",
    save_set: "Enregistrer la série",
    next_exercise: "Exercice suivant",
    finish_session: "Terminer la séance",
    well_done: "Bien joué !",
    feel_great: "Tu peux être fier de toi",
    rate_session: "Note ta séance",
    rate_difficulty: "Difficulté ressentie",
    submit: "Valider",
    history_label: "Historique",
    completed_on: "Terminée le",
    your_pr: "Ton record",
    coach_assigned: "Programmé par ton coach",
    custom_made: "Personnalisé",
    free_label: "Libre",
    no_history: "Aucune séance terminée",
    detail_session: "Détail séance",
    chat_label: "Discussion",
    type_message: "Écris un message...",
    challenge_join_btn: "Rejoindre",
    challenge_quit_btn: "Quitter le défi",
    daily_target: "Objectif quotidien",
    your_progress: "Ta progression",
    library_filter_all: "Tout",
    library_filter_compound: "Polyarticulaire",
    library_filter_isolation: "Isolation",
    library_search_placeholder: "Rechercher un exercice…",
    add_block: "Ajouter un bloc",
    block_label: "Bloc",
    save_session: "Enregistrer la séance",
    onboarding_continue: "Continuer",
    almost_done: "Presque terminé",
    select_at_least_one: "Sélectionne au moins une option",
  },
  en: {
    kg: "kg", km: "km", lbs: "lbs", mi: "mi",
    weight: "Weight", height: "Height",
    primary_goal: "Primary goal", secondary_goal: "Secondary goal",
    fitness_level: "Fitness level",
    training_context: "Training context",
    available_days: "Training days",
    training_location: "Training location",
    equipment: "Available equipment",
    session_duration: "Session duration",
    session_min: "Minimum", session_max: "Maximum",
    injuries: "Injuries / Permanent restrictions",
    no_restrictions: "No restrictions provided",
    exercises: "Exercises", avoided_exercises: "Exercises to avoid",
    favorite_exercises: "Favorite exercises",
    add_exercise: "Add an exercise...",
    from_library: "From library",
    select_exercises: "Select exercises",
    done: "Done", none: "None",
    preferences: "Preferences",
    language_label: "Language", theme_label: "Theme", units_label: "Units",
    health_apps: "Health apps",
    sync_health_data: "Sync your health data with ADAPT.",
    privacy: "Privacy",
    privacy_desc: "Control what your coach can see from your profile.",
    share_weight: "Share weight",
    share_sleep: "Share sleep",
    share_heart_rate: "Share heart rate",
    share_body_fat: "Share body fat",
    share_context: "Share training context",
    coach_only: "Coach-only profile",
    profile_private: "Fully private profile",
    notifications: "Notifications",
    silent_mode: "Disable all notifications",
    morning_notif: "Morning check-in notification",
    session_reminder: "Session reminder",
    progress_update: "Progress update",
    coach_messages: "Coach messages",
    save: "Save", cancel: "Cancel", edit: "Edit",
    connect: "Connect", disconnect: "Disconnect",
    connected: "Connected", not_connected: "Not connected",
    achievement: "Achievement unlocked",
    weekly_recap: "Weekly summary",
    soon: "Coming soon",
    soon_msg: "will be available in a future update.",
    privacy_visibility: "Profile visibility",
    shared_data: "Data shared with coach",
    completion_hint_low: "Complete your profile to personalize your training",
    completion_hint_mid: "Some information is still missing",
    no_injury: "No restrictions noted",
    units_metric: "Kg / Km",
    units_imperial: "Lbs / Mi",
    lang_fr: "Français",
    lang_en: "English",
    theme_dark: "Dark",
    theme_light: "Light",
    theme_system: "Auto",
    goals: "Goals",
    privacy_settings: "Privacy settings",
    lang_label: "Language",
    morning_notif_hour: "Morning reminder time",
    notif_types_label: "Notification types",
    silent_mode_label: "Silent mode",
    privacy_data_desc: "This data is shared with your coach across all views. Disabling a toggle hides the data everywhere.",
    privacy_visibility_desc: "These settings control the global visibility of your profile. Cumulative with the shared data above.",
    health_coming_soon: "Coming soon",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    ok: "OK",
    back: "Back",
    next: "Next",
    previous: "Previous",
    continue: "Continue",
    close: "Close",
    delete: "Delete",
    add: "Add",
    remove: "Remove",
    update: "Update",
    loading: "Loading…",
    retry: "Retry",
    refresh: "Refresh",
    search: "Search",
    filter: "Filter",
    all: "All",
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    week: "Week",
    month: "Month",
    year: "Year",
    day: "Day",
    hour: "Hour",
    minute: "Minute",
    second: "Second",
    minutes: "minutes",
    seconds: "seconds",
    hours: "hours",
    days: "days",
    weeks: "weeks",
    months: "months",
    home: "Home",
    session_tab: "Session",
    stats_tab: "Stats",
    messages_tab: "Messages",
    profile_tab: "Profile",
    welcome: "Welcome",
    hello: "Hello",
    good_morning: "Good morning",
    good_afternoon: "Good afternoon",
    good_evening: "Good evening",
    start_session: "Start session",
    start: "Let's go!",
    resume: "Resume",
    pause: "Pause",
    stop: "Stop",
    finish: "Finish",
    skip: "Skip",
    rest: "Rest",
    sets: "Sets",
    reps: "Reps",
    set: "Set",
    rep: "Rep",
    duration: "Duration",
    rpe: "RPE",
    notes: "Notes",
    note: "Note",
    feedback: "Feedback",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    too_easy: "Too easy",
    just_right: "Just right",
    too_hard: "Too hard",
    cannot_start_session: "Couldn't start this session. Try again.",
    cannot_start_program: "Couldn't start the program. Try again.",
    cannot_log_exercise: "Couldn't log the exercise.",
    cannot_save: "Couldn't save. Try again.",
    cannot_load: "Couldn't load data.",
    network_error: "Network error. Check your connection.",
    session_completed: "Session completed!",
    great_job: "Great job!",
    keep_going: "Keep it up!",
    no_session_today: "No session today",
    next_session: "Next session",
    upcoming_sessions: "Upcoming sessions",
    history: "History",
    library: "Library",
    programs: "Programs",
    challenges: "Challenges",
    badges: "Badges",
    guides: "Guides",
    nutrition: "Nutrition",
    sleep: "Sleep",
    steps: "Steps",
    heart_rate: "Heart rate",
    body_fat: "Body fat",
    bmi: "BMI",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    water: "Water",
    checkin: "Check-in",
    morning_checkin: "Morning check-in",
    daily_checkin: "Daily check-in",
    mood: "Mood",
    energy: "Energy",
    motivation: "Motivation",
    soreness: "Soreness",
    stress: "Stress",
    coach: "Coach",
    athlete: "Athlete",
    message_placeholder: "Write a message…",
    send: "Send",
    no_messages: "No messages",
    new_message: "New message",
    login: "Sign in",
    register: "Sign up",
    logout: "Log out",
    email: "Email",
    password: "Password",
    confirm_password: "Confirm password",
    forgot_password: "Forgot password?",
    reset_password: "Reset password",
    sign_in: "Sign in",
    sign_up: "Sign up",
    invalid_credentials: "Invalid credentials",
    required_field: "Required field",
    invalid_email: "Invalid email",
    password_too_short: "Password too short",
    passwords_dont_match: "Passwords don't match",
    onboarding_welcome: "Welcome to ADAPT",
    onboarding_goal: "What's your goal?",
    onboarding_fitness: "What's your level?",
    onboarding_profile: "Your profile",
    onboarding_invite: "Invite code",
    enter_invite_code: "Enter code",
    skip_for_now: "Skip for now",
    name: "Name",
    first_name: "First name",
    last_name: "Last name",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    birthdate: "Date of birth",
    no_data: "No data",
    empty_state: "Nothing to show yet",
    coming_soon: "Coming soon",
    about: "About",
    version: "Version",
    terms: "Terms of use",
    privacy_policy: "Privacy policy",
    contact: "Contact",
    help: "Help",
    settings: "Settings",
    account: "Account",
    delete_account: "Delete account",
    confirm_logout: "Do you really want to log out?",
    confirm_delete: "This action cannot be undone. Continue?",
    saved: "Saved",
    updated: "Updated",
    deleted: "Deleted",
    sent: "Sent",
    copied: "Copied",
    profile_completed: "PROFILE COMPLETED",
    save_error: "Couldn't save your changes",
    injuries_placeholder: "Ex: left knee pain, fragile shoulder...",
    tap_pencil_to_edit: "Tap the pencil icon to edit",
    health_integration_coming: "Integration coming soon.",
    day_short_lun: "M",
    day_short_mar: "T",
    day_short_mer: "W",
    day_short_jeu: "T",
    day_short_ven: "F",
    day_short_sam: "S",
    day_short_dim: "S",
    loc_gym: "Gym",
    loc_home: "Home",
    loc_outdoor: "Outdoor",
    equip_barbell: "Barbell",
    equip_dumbbell: "Dumbbells",
    equip_kettlebell: "Kettlebell",
    equip_machine: "Machines",
    equip_cable: "Cable",
    equip_bodyweight: "Bodyweight",
    equip_bands: "Bands",
    equip_trx: "TRX",
    goal_strength: "Strength",
    goal_muscle: "Muscle gain",
    goal_fat_loss: "Fat loss",
    goal_performance: "Performance",
    goal_health: "Health",
    goal_aesthetic: "Aesthetics",
    goal_fitness: "General fitness",
    level_beginner: "Beginner",
    level_intermediate: "Intermediate",
    level_advanced: "Advanced",
    level_expert: "Expert",
    sgoal_mobility: "Mobility",
    sgoal_endurance: "Endurance",
    sgoal_flexibility: "Flexibility",
    sgoal_power: "Power",
    sgoal_balance: "Balance",
    sgoal_stress: "Wellness",
    sgoal_sport: "Specific sport",
    privacy_share_weight_label: "Body weight",
    privacy_share_sleep_label: "Sleep quality",
    privacy_share_hr_label: "Heart rate",
    privacy_share_bf_label: "Body fat (%)",
    privacy_share_context_label: "Training context",
    auth_tagline: "Training that adapts to you.",
    no_account_yet: "No account yet?",
    create_account: "Create an account",
    create_my_account: "Create my account",
    create_account_title: "CREATE ACCOUNT",
    join_adapt: "Join ADAPT",
    already_have_account: "Already have an account?",
    sign_in_link: "Sign in",
    forgot_pwd_title: "FORGOT",
    forgot_pwd_title_sub: "PASSWORD",
    forgot_pwd_subtitle: "Enter your email address. You'll receive a link to choose a new password.",
    send_link_btn: "SEND LINK",
    email_sent_title: "Email sent!",
    email_sent_text: "If an account exists with this address, you'll receive a reset link in a few minutes. Check your spam folder too.",
    back_to_login: "Back to sign in",
    email_required: "Email address is required",
    email_password_required: "Email and password are required",
    all_fields_required: "All fields are required",
    pwd_min_8: "Password must be at least 8 characters",
    pwd_strength_weak: "Weak",
    pwd_strength_medium: "Medium",
    pwd_strength_good: "Good",
    pwd_strength_strong: "Strong",
    pwd_min_chars_placeholder: "Min. 8 characters",
    new_pwd_title: "NEW",
    new_pwd_title_sub: "PASSWORD",
    new_password: "New password",
    confirm_password_label: "Confirm password",
    change_my_password: "CHANGE MY PASSWORD",
    pwd_updated: "Password updated!",
    redirecting_login: "Redirecting to sign in…",
    invalid_link: "Invalid link",
    invalid_link_subtitle: "This reset link is invalid or has expired.",
    request_new_link: "Request a new link",
    invalid_or_expired: "Invalid or expired link.",
    error_generic: "An error occurred. Try again.",
    not_found_title: "This screen doesn't exist.",
    go_home: "Back to home",
    no_session_subtitle: "No session scheduled today. Your coach hasn't assigned a program yet.",
    no_session_uppercase: "NO SESSION",
    in_person: "IN PERSON",
    online: "ONLINE",
    adapt_score: "ADAPT SCORE",
    edit_checkin_today: "Edit my check-in today",
    you_will_need: "YOU WILL NEED",
    coach_notes: "COACH NOTES",
    exercises_count_label: "EXERCISES",
    min_label: "MIN",
    guided: "GUIDED",
    board: "BOARD",
    show_details: "Show details",
    hide_details: "Hide",
    loads_at_pct: "Loads at",
    exercise: "EXERCISE",
    planned: "PLANNED",
    adapted: "ADAPTED",
    cannot_validate_session: "Couldn't validate the session",
    cannot_confirm_presence: "Couldn't confirm presence",
    notifications_title: "Notifications",
    no_notifications: "No notifications",
    mark_all_read: "Mark all as read",
    weekly_recap_title: "Weekly recap",
    weekly_recap_empty: "No recap available",
    badges_title: "Badges",
    badges_empty: "No badges unlocked",
    challenges_title: "Challenges",
    join_challenge: "Join challenge",
    progress: "Progress",
    leaderboard: "Leaderboard",
    days_remaining: "days left",
    checkin_title: "Daily check-in",
    checkin_intro: "Take 30 seconds to rate how you feel today.",
    sleep_q: "How did you sleep?",
    energy_q: "What's your energy level?",
    stress_q: "Stress level?",
    soreness_q: "Soreness?",
    motivation_q: "Motivation?",
    pain_q: "Any pain?",
    pain_notes_placeholder: "Briefly describe (optional)",
    cycle_phase_q: "Cycle phase (optional)",
    submit_checkin: "Submit check-in",
    checkin_done: "Check-in saved!",
    checkin_done_subtitle: "Today's session adapts to your state.",
    see_my_session: "See my session",
    guides_title: "Guides",
    guides_empty: "No guides available",
    library_title: "Library",
    library_empty: "No sessions available",
    custom_session_title: "Custom session",
    add_to_session: "Add to session",
    start_custom: "Start session",
    chat_placeholder: "Write a message...",
    onboarding_welcome_title: "Welcome to ADAPT",
    onboarding_welcome_subtitle: "Training that adapts to you.",
    get_started: "Get started",
    onboarding_goal_q: "What's your goal?",
    onboarding_fitness_q: "What's your level?",
    onboarding_profile_q: "Tell us about you",
    onboarding_invite_q: "Do you have an invite code?",
    invite_code_placeholder: "Invite code",
    validate: "Validate",
    skip_step: "Skip",
    tutorial_title: "How it works",
    finish_tutorial: "Got it",
    session_complete_title: "Session complete!",
    session_complete_subtitle: "Great job, be proud of yourself!",
    rate_session_q: "How did you feel?",
    submit_rating: "Submit",
    free_session_title: "Free session",
    free_session_intro: "Build your session on the fly.",
    add_exercise_btn: "Add exercise",
    end_session: "End session",
    history_title: "History",
    history_empty: "No completed sessions",
    feedback_title: "Your feedback",
    submit_feedback: "Send",
    your_session: "Your session",
    detail_title: "Session detail",
    no_exercises: "No exercises",
    sets_label: "sets",
    reps_label: "reps",
    rest_label: "rest",
    badge_cat_special: "Special",
    badge_cat_streak: "Streak",
    badge_cat_sessions: "Sessions",
    badge_cat_pr: "Records",
    my_badges: "MY BADGES",
    weekly_recap_uppercase: "WEEKLY RECAP",
    calculating: "Calculating...",
    no_data_week: "No data for this week yet.",
    sessions_uppercase: "SESSIONS",
    performances_uppercase: "PERFORMANCE",
    vs_prev_week: "vs previous week:",
    avg_adapt_score: "Average ADAPT score",
    avg_rpe: "Average RPE",
    total_volume: "Total volume",
    new_records: "New records",
    no_session_this_week: "No session this week. Start today!",
    just_now: "Just now",
    minutes_ago: "{0} min ago",
    hours_ago: "{0}h ago",
    days_ago: "{0}d ago",
    mark_all_short: "Read all",
    challenge_progress_title: "Challenge progress",
    challenge_completed: "Challenge complete",
    challenge_failed: "Challenge failed",
    sleep_hours: "Hours of sleep",
    very_bad: "Very bad",
    bad: "Bad",
    ok_label: "OK",
    good: "Good",
    very_good: "Very good",
    very_low: "Very low",
    low: "Low",
    high: "High",
    very_high: "Very high",
    save_checkin: "Submit check-in",
    saving: "Saving…",
    welcome_aboard: "Welcome aboard!",
    your_score_today: "Your score today",
    session_will_adapt: "Your session adapts to your state.",
    next_step: "Next step",
    log_in: "Sign in",
    have_invite: "I have a code",
    skip_invite: "Continue without code",
    invite_sent: "Request sent to your coach!",
    invite_invalid: "Invalid code",
    your_first_name: "Your first name",
    your_last_name: "Your last name",
    select_goal: "Select your main goal",
    select_level: "Select your level",
    finish_setup: "Finish",
    free_session_intro_long: "Build your session on the fly. Add the exercises you want.",
    no_exercise_added: "No exercise added",
    end_free_session: "End session",
    save_set: "Save set",
    next_exercise: "Next exercise",
    finish_session: "Finish session",
    well_done: "Well done!",
    feel_great: "You can be proud of yourself",
    rate_session: "Rate your session",
    rate_difficulty: "Perceived difficulty",
    submit: "Submit",
    history_label: "History",
    completed_on: "Completed on",
    your_pr: "Your record",
    coach_assigned: "Assigned by your coach",
    custom_made: "Custom",
    free_label: "Free",
    no_history: "No completed sessions",
    detail_session: "Session detail",
    chat_label: "Chat",
    type_message: "Write a message...",
    challenge_join_btn: "Join",
    challenge_quit_btn: "Quit challenge",
    daily_target: "Daily target",
    your_progress: "Your progress",
    library_filter_all: "All",
    library_filter_compound: "Compound",
    library_filter_isolation: "Isolation",
    library_search_placeholder: "Search an exercise…",
    add_block: "Add a block",
    block_label: "Block",
    save_session: "Save session",
    onboarding_continue: "Continue",
    almost_done: "Almost done",
    select_at_least_one: "Select at least one option",
  },
};

export function useT() {
  const { language } = usePreferences();
  return useCallback(
    (key: string, fallback?: string): string => {
      const dict = TRANSLATIONS[language] ?? TRANSLATIONS.fr;
      return dict[key] ?? fallback ?? key;
    },
    [language]
  );
}

export function useUnitsLabel() {
  const { units } = usePreferences();
  return {
    weight: units === "imperial" ? "lbs" : "kg",
    distance: units === "imperial" ? "mi" : "km",
    isImperial: units === "imperial",
  };
}

export function useThemeColors() {
  const { resolvedTheme } = usePreferences();
  return resolvedTheme === "light" ? LIGHT_COLORS : DARK_COLORS;
}
